// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UretimTakip.DataAccess.Context;

#nullable disable

namespace UretimTakip.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260703131445_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UretimTakip.core.Entities.Depo", b =>
                {
                    b.Property<Guid>("DepoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DepoAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DepoKodu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IrtibatBilgisi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("SorumluKisi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepoId");

                    b.ToTable("Depolar", (string)null);
                });

            modelBuilder.Entity("UretimTakip.core.Entities.Stok", b =>
                {
                    b.Property<Guid>("StokId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DepoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Miktar")
                        .HasColumnType("int");

                    b.Property<DateTime>("SonGuncellenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("StokKodu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UrunId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("StokId");

                    b.HasIndex("DepoId");

                    b.HasIndex("UrunId");

                    b.ToTable("Stoklar", (string)null);
                });

            modelBuilder.Entity("UretimTakip.core.Entities.Urun", b =>
                {
                    b.Property<Guid>("UrunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Agirlik")
                        .HasColumnType("float");

                    b.Property<string>("Akim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Desi")
                        .HasColumnType("float");

                    b.Property<double>("Genislik")
                        .HasColumnType("float");

                    b.Property<string>("Guc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("HariciKodu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kategori")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Marka")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OlcuBirimi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("SistemUrunKodu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrunAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Uzunluk")
                        .HasColumnType("float");

                    b.Property<string>("Voltaj")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Yukseklik")
                        .HasColumnType("float");

                    b.HasKey("UrunId");

                    b.ToTable("Urunler", (string)null);
                });

            modelBuilder.Entity("UretimTakip.core.Entities.Stok", b =>
                {
                    b.HasOne("UretimTakip.core.Entities.Depo", null)
                        .WithMany()
                        .HasForeignKey("DepoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UretimTakip.core.Entities.Urun", null)
                        .WithMany()
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
