// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UretimTakip.DataAccess.Context;

#nullable disable

namespace UretimTakip.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260825191836_AddIsDeletedToStok")]
    partial class AddIsDeletedToStok
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UretimTakip.core.Entities.Bildirim", b =>
                {
                    b.Property<Guid>("BildirimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Mesaj")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("OkunduMu")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("OkunmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("BildirimId");

                    b.ToTable("Bildirimler", (string)null);
                });

            modelBuilder.Entity("UretimTakip.core.Entities.Depo", b =>
                {
                    b.Property<Guid>("DepoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DepoAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DepoKodu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IrtibatBilgisi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("Konum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("SorumluKisi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepoId");

                    b.ToTable("Depolar", (string)null);

                    b.HasData(
                        new
                        {
                            DepoId = new Guid("a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d"),
                            Adres = "",
                            DepoAdi = "Merkez Depo",
                            DepoKodu = "",
                            IrtibatBilgisi = "",
                            IsActive = true,
                            IsArchived = false,
                            Konum = "Eskişehir Tepebaşı",
                            OlusturulmaTarihi = new DateTime(2026, 8, 25, 19, 18, 35, 498, DateTimeKind.Utc).AddTicks(2775),
                            SorumluKisi = ""
                        });
                });

            modelBuilder.Entity("UretimTakip.core.Entities.Hedef", b =>
                {
                    b.Property<Guid>("HedefId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("HedeflenenTutar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("MevcutTutar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<bool>("TamamlandiMi")
                        .HasColumnType("bit");

                    b.HasKey("HedefId");

                    b.ToTable("Hedefler", (string)null);
                });

            modelBuilder.Entity("UretimTakip.core.Entities.Siparis", b =>
                {
                    b.Property<Guid>("SiparisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CariId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("SiparisNumarasi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SiparisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ToplamTutar")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("SiparisId");

                    b.ToTable("Siparis", (string)null);
                });

            modelBuilder.Entity("UretimTakip.core.Entities.SiparisDetay", b =>
                {
                    b.Property<Guid>("SiparisDetayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("BirimFiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Miktar")
                        .HasColumnType("int");

                    b.Property<Guid>("SiparisId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UrunId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SiparisDetayId");

                    b.ToTable("SiparisDetay", (string)null);
                });

            modelBuilder.Entity("UretimTakip.core.Entities.Stok", b =>
                {
                    b.Property<Guid>("StokId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DepoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Miktar")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SonGuncellenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("StokKodu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UrunId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("StokId");

                    b.HasIndex("DepoId");

                    b.HasIndex("UrunId");

                    b.ToTable("Stoklar", (string)null);

                    b.HasData(
                        new
                        {
                            StokId = new Guid("11223344-5566-7788-9900-aabbccddeeff"),
                            DepoId = new Guid("a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d"),
                            IsDeleted = false,
                            Miktar = 50,
                            OlusturulmaTarihi = new DateTime(2026, 8, 25, 19, 18, 35, 498, DateTimeKind.Utc).AddTicks(3327),
                            SonGuncellenmeTarihi = new DateTime(2026, 8, 25, 19, 18, 35, 498, DateTimeKind.Utc).AddTicks(3321),
                            StokKodu = "",
                            UrunId = new Guid("f6e5d4c3-b2a1-0f9e-8d7c-6b5a4f3db1ba")
                        });
                });

            modelBuilder.Entity("UretimTakip.core.Entities.Urun", b =>
                {
                    b.Property<Guid>("UrunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Agirlik")
                        .HasColumnType("float");

                    b.Property<string>("Akim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Desi")
                        .HasColumnType("float");

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("Genislik")
                        .HasColumnType("float");

                    b.Property<string>("Guc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("HariciKodu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Kategori")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Marka")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OlcuBirimi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("SistemUrunKodu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrunAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Uzunluk")
                        .HasColumnType("float");

                    b.Property<string>("Voltaj")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Yukseklik")
                        .HasColumnType("float");

                    b.HasKey("UrunId");

                    b.ToTable("Urunler", (string)null);

                    b.HasData(
                        new
                        {
                            UrunId = new Guid("f6e5d4c3-b2a1-0f9e-8d7c-6b5a4f3db1ba"),
                            Agirlik = 0.0,
                            Akim = "",
                            Desi = 0.0,
                            Fiyat = 45000m,
                            Genislik = 0.0,
                            Guc = "",
                            HariciKodu = "",
                            IsDeleted = false,
                            Kategori = "",
                            Marka = "Apple",
                            Model = "iPhone 15",
                            OlcuBirimi = "",
                            OlusturulmaTarihi = new DateTime(2026, 8, 25, 19, 18, 35, 498, DateTimeKind.Utc).AddTicks(3242),
                            SistemUrunKodu = "TEL-001",
                            UrunAdi = "Akıllı Telefon",
                            Uzunluk = 0.0,
                            Voltaj = "",
                            Yukseklik = 0.0
                        });
                });

            modelBuilder.Entity("UretimTakip.core.Models.Cari", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CariKodu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CariTuru")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Cariler", (string)null);
                });

            modelBuilder.Entity("UretimTakip.core.Entities.Stok", b =>
                {
                    b.HasOne("UretimTakip.core.Entities.Depo", null)
                        .WithMany()
                        .HasForeignKey("DepoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UretimTakip.core.Entities.Urun", null)
                        .WithMany()
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
