// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UretimTakip.DataAccess.Context;

#nullable disable

namespace UretimTakip.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UretimTakip.core.Entities.Depo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DepoAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DepoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DepoKodu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IrtibatBilgisi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("Konum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("SorumluKisi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Depolar", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d"),
                            Ad = "Merkez Depo",
                            Adres = "",
                            DepoAdi = "",
                            DepoId = new Guid("a60c5b51-6d53-426c-b6a7-2e5648a154e5"),
                            DepoKodu = "",
                            IrtibatBilgisi = "",
                            IsActive = true,
                            IsArchived = false,
                            Konum = "Eskişehir Tepebaşı",
                            OlusturulmaTarihi = new DateTime(2026, 7, 3, 15, 41, 56, 489, DateTimeKind.Utc).AddTicks(1975),
                            SorumluKisi = ""
                        });
                });

            modelBuilder.Entity("UretimTakip.core.Entities.Stok", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Adet")
                        .HasColumnType("int");

                    b.Property<Guid>("DepoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Miktar")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SonGuncellenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("StokId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StokKodu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UrunId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DepoId");

                    b.HasIndex("UrunId");

                    b.ToTable("Stoklar", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11223344-5566-7788-9900-aabbccddeeff"),
                            Adet = 50,
                            DepoId = new Guid("a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d"),
                            Miktar = 0,
                            OlusturulmaTarihi = new DateTime(2026, 7, 3, 15, 41, 56, 489, DateTimeKind.Utc).AddTicks(2198),
                            SonGuncellenmeTarihi = new DateTime(2026, 7, 3, 15, 41, 56, 489, DateTimeKind.Utc).AddTicks(2195),
                            StokId = new Guid("1ff0741f-3591-432c-ac47-6a7fe404f5cb"),
                            StokKodu = "",
                            UrunId = new Guid("f6e5d4c3-b2a1-0f9e-8d7c-6b5a4f3db1ba")
                        });
                });

            modelBuilder.Entity("UretimTakip.core.Entities.Urun", b =>
                {
                    b.Property<Guid>("UrunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Agirlik")
                        .HasColumnType("float");

                    b.Property<string>("Akim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Desi")
                        .HasColumnType("float");

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("Genislik")
                        .HasColumnType("float");

                    b.Property<string>("Guc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("HariciKodu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kategori")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Marka")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OlcuBirimi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("SistemUrunKodu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrunAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Uzunluk")
                        .HasColumnType("float");

                    b.Property<string>("Voltaj")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Yukseklik")
                        .HasColumnType("float");

                    b.HasKey("UrunId");

                    b.ToTable("Urunler", (string)null);

                    b.HasData(
                        new
                        {
                            UrunId = new Guid("f6e5d4c3-b2a1-0f9e-8d7c-6b5a4f3db1ba"),
                            Agirlik = 0.0,
                            Akim = "",
                            Desi = 0.0,
                            Fiyat = 45000m,
                            Genislik = 0.0,
                            Guc = "",
                            HariciKodu = "",
                            Kategori = "",
                            Marka = "Apple",
                            Model = "iPhone 15",
                            OlcuBirimi = "",
                            OlusturulmaTarihi = new DateTime(2026, 7, 3, 15, 41, 56, 489, DateTimeKind.Utc).AddTicks(2173),
                            SistemUrunKodu = "TEL-001",
                            UrunAdi = "Akıllı Telefon",
                            Uzunluk = 0.0,
                            Voltaj = "",
                            Yukseklik = 0.0
                        });
                });

            modelBuilder.Entity("UretimTakip.core.Entities.Stok", b =>
                {
                    b.HasOne("UretimTakip.core.Entities.Depo", null)
                        .WithMany()
                        .HasForeignKey("DepoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UretimTakip.core.Entities.Urun", null)
                        .WithMany()
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
