<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\UretimTakip.core\UretimTakip.core.csproj" />
    <ProjectReference Include="..\UretimTakip.DataAccess\UretimTakip.DataAccess.csproj" />
  </ItemGroup>

</Project>
